// =====================================================
//  SPITWIT — Prompt Data & Generation
// =====================================================

export const PROMPT_PACKS = {
  party: [
    "The worst thing to say at a birthday party",
    "A rejected name for a new cocktail",
    "What the DJ actually plays after everyone asks him to stop",
    "The worst Uber rating explanation",
    "What you find under the couch at a frat house",
    "A bad reason to start a conga line",
    "The most awkward thing to drop on the dance floor",
    "What the bouncer is really writing in his notebook",
    "A terrible theme for a bachelorette party",
    "The world's most disappointing party trick",
    "What people regret saying in the group chat",
    "The least helpful thing to say to someone who's lost at a festival",
    "A party game that ends friendships",
    "The worst thing to find in the punch bowl",
    "What the designated driver is secretly thinking",
    "A terrible icebreaker question for a house party",
    "The most passive-aggressive thing to write on a birthday card",
    "A piñata filling that kills the mood",
    "What the neighbor's complaint letter actually says",
    "The worst plus-one to bring to a wedding",
  ],
  dark: [
    "A cheerful name for something terrifying",
    "What the skeleton in the closet is actually doing",
    "The worst horoscope ever written",
    "A bad time to discover your GPS is wrong",
    "The world's most depressing motivational poster",
    "What ghosts are really haunting people about",
    "A terrible name for a crisis hotline",
    "The last thing anyone wants to read on a fortune cookie",
    "The product that exists in real life and absolutely should not",
    "The most unsettling thing a child can say at dinner",
    "The most cheerful text you could send someone to make them immediately panic",
    "What the dentist is actually thinking",
    "The world's worst self-help book title",
    "What happens when you mix up your therapist and your boss's email",
    "A bad thing to discover mid-skydive",
    "The saddest item on a to-do list",
    "What heaven's Yelp reviews actually say",
    "A terrible name for a funeral home",
    "The most anticlimactic apocalypse scenario",
    "What the fine print on your soul contract says",
  ],
  wholesome: [
    "What grandma accidentally sent to the family group chat",
    "The most wholesome thing a golden retriever is thinking",
    "The completely wrong thing a kid believed for years that was somehow better than the truth",
    "What the class hamster writes in its diary",
    "The nicest possible reason someone's crying on a park bench",
    "The cutest misconception a kid held for way too long before anyone corrected them",
    "The cutest misunderstanding between two old people",
    "What your houseplant would say if it could talk",
    "A compliment so sincere it becomes awkward",
    "What the mailman's highlight of his day is",
    "The lunchbox note a parent left that completely backfired",
    "What sunshine would say if it were a person",
    "A bedtime story that's way too comforting",
    "What the neighborhood squirrel has learned about humans",
    "The best possible outcome of a wrong number",
    "What puppies actually dream about",
    "What your dog thinks you're doing every single time you leave the house",
    "The most wholesome reason someone has ever ugly-cried in public",
    "The thing a grandparent said with complete confidence that turned out to be unhinged",
    "What your childhood stuffed animal would say to you now",
  ],
  internet: [
    "The most embarrassing thing to Google while your screen is visible to strangers",
    "A meme format that somehow explains your entire personality",
    "What ChatGPT says when you ask it something actually useful",
    "The WiFi password you'll never give to houseguests",
    "A Spotify Wrapped result that shatters your self-image",
    "The most disappointing TikTok rabbit hole you fell into",
    "What Reddit thinks is a totally reasonable thing to argue about for six hours",
    "The worst possible title for a YouTube channel you'd definitely still watch",
    "A tweet that gets ratio'd harder than anyone ever deserved",
    "What the Discord server you never left is still arguing about",
    "The most unhinged thing anyone's ever put in a Yelp review",
    "An NFT that somehow becomes the most important cultural artifact of the decade",
    "What the comment section of a recipe blog is actually about",
    "The LinkedIn post that made you lose faith in the concept of professionals",
    "A Wikipedia rabbit hole that takes you somewhere genuinely dark",
    "What the algorithm thinks you want based on your last three searches",
    "A podcast topic so niche it has exactly 11 listeners — and you're one of them",
    "The browser tab you've kept open for six months and will never actually read",
    "What happens when you leave a group chat on read for too long",
    "The most passive-aggressive use of a thumbs-up emoji",
    "What Elon Musk's next company is definitely going to be called",
    "The most cursed keyboard shortcut you've accidentally discovered",
    "A tech startup name that's either a billion-dollar idea or a desperate cry for help",
    "What 'main character energy' actually looks like from the outside",
    "The most suspiciously specific subreddit that also perfectly describes your life",
    "A viral challenge so bad it briefly makes you optimistic about society for being so dumb",
    "What your camera roll says about you to someone who doesn't know you",
    "The search autocomplete that you had to clear immediately",
  ],
  work: [
    "A job title that sounds impressive but means absolutely nothing",
    "The most creative out-of-office message ever written",
    "What the office printer is actually printing when nobody's looking",
    "A Slack message that could either be completely innocent or a total power move",
    "The passive-aggressive way to decline a meeting that still sounds professional",
    "What 'just circling back on this' really means",
    "A performance review comment that haunts you for years",
    "The strangest item anyone has ever expensed and actually gotten approved",
    "What the company values poster in the breakroom is actually saying",
    "The most creative way to admit you have no idea what's going on in a meeting",
    "A team-building activity so bad it accidentally becomes the thing that bonds everyone",
    "What the intern's first week is actually teaching them",
    "The unwritten rule every office has that nobody explains to new hires",
    "A buzzword that means nothing but appears in every third sentence of every meeting",
    "What the person who always brings homemade cookies to work actually wants in return",
    "The most creative name for an Excel spreadsheet that holds way too much power",
    "What happens at the company offsite that never makes it into the recap email",
    "The subject line that guarantees your email is never opened",
    "What 'innovative' means to someone who has never once innovated",
    "A job interview question that accidentally reveals everything wrong with the company",
    "The most creative way to say you're quitting without technically saying you're quitting",
    "What the 'culture fit' interview is really screening for",
    "A project management tool that somehow makes everything harder while claiming to help",
    "The phrase that makes every genuinely good idea sound terrible in a meeting",
    "What the weekly all-hands meeting replaced that everyone secretly misses",
    "The most elaborate way to avoid replying to an email for three weeks",
    "What 'synergy' looked like the one time it actually happened",
    "The unspoken hierarchy of which meeting room you're allowed to book",
  ],
};

// All built-in prompts combined
const ALL_PROMPTS = [
  ...PROMPT_PACKS.party,
  ...PROMPT_PACKS.dark,
  ...PROMPT_PACKS.wholesome,
  // GENERAL BATCH
  "A terrible first line of a novel",
  "The most useless superpower",
  "A rejected slogan for a fast food chain",
  "What aliens are actually observing about Earth",
  "The worst possible name for a children's book",
  "What your pet is plotting while you're at work",
  "A bad sign you've been on the internet too long",
  "The most suspicious thing to Google at 3AM",
  "A job title that sounds important but isn't",
  "What robots complain about at their union meetings",
  "The laziest solution to climate change",
  "A terrible supervillain origin story",
  "What really happens at the bottom of the ocean",
  "The worst possible last words",
  "A bad reason to call in sick",
  "What the voices in your GPS really want",
  "The most dangerous item at a garage sale",
  "A rejected name for a pharmaceutical drug",
  "What a time traveler would be most disappointed by",
  "The least romantic thing to say during a proposal",
  "A terrible pitch for a new TV show",
  "What kids think adults do all day",
  "The world's most boring superhero",
  "A bad piece of advice from a fortune teller",
  "What the Moon is hiding from us",
  "The saddest emoji combination",
  "A rejected Olympic sport",
  "What Santa does in July",
  "The worst way to break up with someone via emoji",
  "A terrible name for a dating app",
  "The thing you do in public that you assume nobody notices but everyone does",
  "The most unhelpful warning label",
  "A bad reason to become a pirate",
  "What the first rule of a secret society should be",
  "The worst thing to find in a fortune cookie",
  "A terrible business idea that somehow gets funded",
  "What ants are actually saying when they march",
  "The most polite insult ever spoken",
  "The made-up excuse that somehow worked and you've never recovered from",
  "What happens in the town where all the missing socks go",
  "The worst possible name for a baby",
  "A rejected slogan for a gym",
  "What your search history would confess about you",
  "The most awkward thing to order at a restaurant",
  "A terrible self-defense move",
  "The most unhinged hill someone has died on in an argument",
  "The worst theme for a children's birthday party",
  "A bad thing to say during a job interview",
  "What clouds are made of, according to a five-year-old",
  "The most useless item in a survival kit",
  "A terrible name for a sports team",
  "What an AI really thinks about humans",
  "The least inspirational place to hang a motivational quote",
  "A bad reason to start learning a new language",
  "What fish talk about when humans aren't watching",
  "The most unsettling way to greet a stranger",
  "A terrible password that somehow becomes standard practice",
  "The fashion choice from your past you genuinely cannot explain or defend",
  "The worst way to announce a pregnancy",
  "A rejected name for a new country",
  "What parents think 'the cloud' is",
  "The most unusual thing to collect",
  "A terrible name for a life coach",
  "The lie you told once that snowballed way too far to correct",
  "The worst advice column response ever published",
  "A bad slogan for a dentist office",
  "The thing you own that you genuinely cannot explain why you bought",
  "The most disappointing magic trick",
  "A terrible way to end a business email",
  "What the elevator is judging you for",
  "The worst addition to a pizza",
  "A bad motivational speech opener",
  "What a spider thinks every time you use a broom",
  "The most ineffective diet",
  "A terrible museum exhibit",
  "What tourists misunderstand about your city",
  "The worst ice cream flavor ever invented",
  "A bad reason to become a doctor",
  "What the moon sees on a typical Friday night",
  "The most confusing thing about modern life",
  "A terrible app idea that somehow gets 5 stars",
  "The weirdest unwritten rule everyone somehow already knows",
  "The worst camping advice",
  "A rejected mascot for a professional sports team",
  "What the number 4 is insecure about",
  "The most unnecessary life hack",
  "A terrible name for a therapy practice",
  "What dogs are really barking about",
  "The worst possible sequel to a beloved film",
  "A bad fortune for a Magic 8-Ball",
  "What office plants witness every day",
  "The most suspicious thing someone can say in a library",
  "A terrible name for a yoga class",
  "What teenagers think adulthood is like",
  "The world's worst handshake",
  "A bad reason to call the police",
  "What would happen if elevators had Yelp reviews",
  "The least helpful doctor's diagnosis",
  "A terrible reason to quit your job",
  "What vending machines are angry about",
  "The most over-dramatic weather report",
  "A bad slogan for a hot air balloon company",
  "What happens when nobody is watching the Roomba",
  "The worst travel souvenir",
  "A terrible tagline for a mattress store",
  "What mannequins discuss after closing time",
  "The most awkward family photo caption",
  "A bad idea for a mobile game",
  "What the last dinosaur was thinking",
  "The worst way to start a campfire story",
  "A terrible children's toy recalled immediately",
  "What your refrigerator knows about you",
  "The most useless degree you could earn",
  "A bad reason to become a vegetarian",
  "What would happen if trees could walk",
  "The worst possible Wi-Fi name",
  "A terrible name for a charity",
  "What pigeons are actually saying",
  "The most terrifying knock-knock joke punchline",
  "A bad item to put on a resume",
  "What would happen if dogs could drive",
  "The worst name for a restaurant",
  "A terrible idea for a company retreat",
  "What the sun thinks of us wearing sunscreen",
  "The most anticlimactic treasure hunt reward",
  "The phrase that sounds like a threat even when it's completely innocent",
  "What a shopping cart thinks as it rolls away in the parking lot",
  "The worst possible tour guide script",
  "A terrible reason to start a podcast",
  "What happens in a town where everyone can read minds",
  "The most unsettling greeting card message",
  "A bad idea for a new holiday tradition",
  "What office staplers gossip about",
  "The worst name for a new planet",
  "A terrible reason to call a meeting",
  "What happens at the world's least exciting theme park",
  "The most confusing street name in a city",
  "A bad name for a cooking show",
  "The face you make when you're pretending to understand something you absolutely don't",
  "The worst piece of furniture ever invented",
  "A terrible reason to join a cult",
  "What would happen if shadows became sentient",
  "The most suspicious thing on a grocery list",
  "A bad add-on feature for a self-driving car",
  "What coins in a wishing fountain wish for",
  "The worst icebreaker for a support group",
  "A terrible reality TV show concept",
  "What happens in the secret society of people who wake up before 5AM",
  "The most worrying thing to find in a library's lost and found",
  "A bad line to open a best man speech",
  "The fake name someone gives when they definitely don't want to be found",
  "The worst name for a craft beer",
  "A terrible dating profile opener",
  "What squirrels really do with all those acorns",
  "The most suspicious thing written in a yearbook",
  "A bad name for a cruise ship",
  "What happens if you take astrology too literally",
  "The worst possible theme for a school dance",
  "A terrible way to end a TED talk",
  "What the office microwave has seen",
  "The most confusing thing about sleep",
  "A bad marketing strategy for selling cheese",
  "What would happen if hair grew back instantly after cutting",
  "The worst hidden fee on a hotel bill",
  "A terrible explanation for being late to a meeting",
  "What traffic lights think about during rush hour",
  "The most passive-aggressive office kitchen sign",
  "A bad warning label for a trampoline",
  "The most unconvincing lie ever delivered with complete unearned confidence",
  "The worst reality show for senior citizens",
  "A terrible name for a perfume",
  "What would happen if libraries could fine people for emotional overreactions",
  "The most unnecessary invention of the last decade",
  "A bad slogan for a moving company",
  "What vegetables whisper to each other in the produce aisle",
  "The worst name for a band",
  "A terrible life lesson learned from social media",
  "What would happen if dreams were publicly streamed",
  "The most unfortunate autocorrect message",
  "A bad name for a nonprofit",
  "What escalators think about people who just stand there",
  "The worst idea for a workout class",
  "A terrible plot twist in an otherwise wholesome film",
  "What the cursor thinks when you won't stop clicking",
  "The most uncomfortable silence in history",
  "A bad name for a meditation app",
  "What would happen if people had loading screens",
  "The worst way to discover your house is haunted",
  "A terrible name for a new currency",
  "What houseplants are silently judging you for",
  "The most suspicious reason to know exactly how many steps you've taken today",
  "A bad introduction at a networking event",
  "What Siri secretly thinks of your questions",
  "The worst career pivot from politician to influencer",
  "A terrible way to describe your personality on a first date",
  "What the barista is actually writing on your cup",
  "The most passive-aggressive way to give a gift",
  "A bad name for a power outage preparedness kit",
  "What a city pigeon knows that you don't",
  "The worst reason to quit a gym in January",
  "A terrible name for a home security system",
  "What the loading bar thinks about when it slows to 99%",
  "The most useless piece of trivia you actually know",
  "A bad name for a haircut",
  "What an alarm clock thinks about on weekends",
  "The worst motivational poster for a hospital waiting room",
  "A terrible response to 'How are you?'",
  "What would happen if résumés had to include embarrassing moments",
  "The least impressive flex",
  "A bad name for a co-working space",
  "What a pothole thinks when a car hits it",
  "The worst advice for someone starting a diet",
  "A terrible name for a new airline",
  "What would happen if every notification you ignored became sentient",
  "The most elaborate excuse for forgetting a birthday",
  "A bad slogan for a car dealership",
  "What desk chairs know about their owners",
  "The worst name for a startup",
  "A terrible life lesson you learned way too late",
  "What a grocery store cart thinks of self-checkout",
  "The most overhyped thing about adulthood",
  "A bad name for a home improvement show",
  "What would happen if people had expiration dates printed on them",
  "The worst possible thing to say to a coworker on Monday morning",
  "A terrible reason to avoid going to the doctor",
  "What happens when a robot becomes sentient during its shift at a call center",
  "The most suspicious thing overheard on public transit",
  "A bad name for a space mission",
  "What would happen if your conscience had a Yelp page",
  "The worst possible tourist attraction",
  "A terrible tip jar message",
  "The thing you swore you'd never do like your parents and are absolutely doing now",
  "The most politely devastating thing a teacher has written on a paper",
  "A bad replacement for a GPS",
  "What your bank statement says about your personality",
  "The worst surprise ending to a children's story",
  "A terrible name for a new Olympic event",
  "What would happen if everyone could see each other's browser history",
  "The most overdramatic way to quit a job",
  "A bad slogan for a public library",
  "The specific sound effect your body makes that you've decided to just ignore forever",
  "The worst life advice you've actually received",
  "A terrible way to introduce yourself at a dinner party",
  "What the moon actually thinks of the tides",
  "The most over-engineered solution to a simple problem",
  "A bad name for a social media platform",
  "What would happen if every lie someone told turned their nose slightly red",
  "The worst prank that accidentally becomes a tradition",
  "A terrible alternative to coffee",
  "What a smartphone notices about its owner that it would never say",
  "The most unsettling thing about mirrors",
  "A bad title for a self-published memoir",
  "What would happen if music played automatically whenever you walked into a room",
  "The worst reason to end a friendship",
  "A terrible way to celebrate a promotion",
  "The secret skill you have that would confuse anyone who found out about it",
  "The most ambitious thing to do on a lazy Sunday",
  "A bad slogan for sunscreen",
  "What your college roommate remembers about you",
  "The worst trend that started as a joke",
  "A terrible reason to run for president",
  "What a treadmill thinks during a New Year's resolution rush",
  "The most underwhelming thing to go viral",
  "A bad name for a political party",
  "What would happen if people broadcast live commentary on their own life",
  "The worst thing to find in your annual performance review",
  "A terrible addition to a wedding vow",
  "What would happen if office chairs could unionize",
  "The most confusing thing about the English language",
  "A bad replacement for a smoke alarm",
  "What a broken ATM dreams about",
  "The worst possible motivational quote on a gym wall",
  "A terrible sequel to a beloved game show",
  "What would happen if every meeting that could have been an email became a puppet show instead",
  // BATCH 2
  "The least intimidating gang name",
  "A terrible slogan for a funeral livestream service",
  "What your Uber driver actually thinks when you give 4 stars",
  "The most passive-aggressive way to say you're fine",
  "A bad reason to get a tattoo",
  "What office printers are plotting",
  "The worst thing to shout at a library",
  "A rejected tagline for a water brand",
  "What happens at the world's most boring heist",
  "The worst possible ringtone for a job interview",
  "A terrible name for a true crime podcast",
  "What your Netflix algorithm knows about you that you don't",
  "The least motivating gym name",
  "A bad plot twist in a cooking competition",
  "The unspoken competition at the gym that nobody admits to having",
  "The worst thing to say while cutting someone's hair",
  "A terrible reason to go on a reality dating show",
  "The made-up rule you enforce in your house that nobody has ever questioned",
  "The most cursed thing to find in an Airbnb",
  "A bad reason to start a neighborhood watch",
  "The text you drafted, deleted, and redrafted four times before sending something completely different",
  "The worst surprise in a birthday cake",
  "A terrible job for someone with no patience",
  "What shopping mall food courts are actually serving",
  "The most uncomfortable conversation to overhear in an elevator",
  "A bad reason to move to another country",
  "What happens when you let autocorrect write your wedding vows",
  "The least romantic romantic comedy plot",
  "A terrible mascot for a hospital",
  "What hotel pillows have witnessed",
  "The worst reason to call your ex",
  "A bad name for a true crime documentary",
  "What would happen if apologies had expiration dates",
  "The most suspicious thing to order at a fast food drive-through at midnight",
  "A terrible name for twins",
  "What the 'reply all' button would say if it could feel regret",
  "The worst theme for a gender reveal",
  "A bad reason to become a life coach",
  "What your shadow does when you're not looking",
  "The most overdressed occasion you could attend",
  "A terrible warning label for a motivational book",
  "What happens when a ghost can't figure out why they're still haunting",
  "The most suspicious reason to cancel plans",
  "A bad name for a luxury car",
  "What the last piece of office birthday cake thinks",
  "The worst possible class field trip destination",
  "A terrible slogan for a mattress company",
  "What would happen if texting was replaced with interpretive dance",
  "The most anticlimactic thing to go to jail for",
  "A bad name for a children's cartoon",
  "What a weather app actually thinks about you constantly checking it",
  "The worst possible way to announce you're vegan",
  "A terrible addition to the school curriculum",
  "What traffic jams are actually for",
  "The most unnecessary product ever invented",
  "A bad reason to challenge someone to a duel",
  "What staplers say behind scissors' back",
  "The worst place to have an epiphany",
  "A terrible reason to learn a musical instrument",
  "The specific type of person who is the exact same everywhere they go",
  "The most unsettling children's song you could write",
  "A bad excuse for forgetting someone's name",
  "What happens in the waiting room of the afterlife",
  "The worst thing your smart home device could say",
  "A terrible name for a bakery",
  "What paint watches people do in their homes",
  "The most politely devastating rejection letter",
  "A bad alternative to shaking hands",
  "What would happen if every compliment had a disclaimer",
  "The least impressive magic show",
  "A terrible reason to move to a different seat on a plane",
  "What a to-do list thinks of its creator",
  "The worst hashtag to trend",
  "A bad name for a streaming service",
  "What would happen if people had to narrate their own lives out loud",
  "The most unnecessary disclaimer",
  "A terrible plot for a Pixar movie",
  "What vending machine D7 thinks about never being chosen",
  "The worst way to break the news you're moving away",
  "A bad reason to write a strongly worded letter",
  "What happens at the annual conference for forgotten passwords",
  "The most suspicious thing to keep in your car",
  "A terrible name for a detective agency",
  "What a Wikipedia article thinks about being edited at 2AM",
  "The worst way to describe your job at a party",
  "A bad reason to knock on a stranger's door",
  "What would happen if procrastination was an Olympic sport",
  "The least effective battle cry",
  "A terrible icebreaker for a job interview",
  "What your immune system says when you finally get a good night's sleep",
  "The worst possible way to say 'I love you' for the first time",
  "A bad name for a chain of hotels",
  "What happens when a motivational speaker loses all motivation",
  "The most suspicious LinkedIn endorsement",
  "A terrible reason to start a fire",
  "What the snooze button thinks every morning",
  "The worst possible thing to say in a job resignation letter",
  "A bad name for a new country founded in your backyard",
  "What would happen if every excuse you made became publicly visible",
  "The most unnecessary celebrity beef",
  "A terrible slogan for a dentist who just found out they hate teeth",
];

// Deduplicate
export const UNIQUE_PROMPTS = [...new Set(ALL_PROMPTS)];

// ===== PERSONAL PROMPT TEMPLATES =====
export const PERSONAL_PROMPT_TEMPLATES = [
  "What is [A] definitely hiding from their family?",
  "The most [A]-coded response to a text message",
  "What [A] orders at a restaurant to assert dominance",
  "The thing [A] Googles at 2AM that they'd never admit",
  "What [A]'s villain origin story looks like",
  "The award [A] would win at the world's most honest award show",
  "What [A] and [B] would name their band",
  "The reason [A] would get kicked out of a museum",
  "What [A]'s spirit animal says behind their back",
  "The hobby [A] claims to have that nobody's ever actually seen them do",
  "What [A] is definitely lying about on their resume",
  "The most [A] thing [A] has ever done",
  "What [A] and [B] would argue about on a road trip",
  "What [A] thinks about during an awkward silence",
  "The conspiracy theory [A] secretly believes",
  "What [A] brings to every potluck no matter what",
  "The most likely reason [A] would get banned from a buffet",
  "What [A] is actually doing when they say they're 'working from home'",
  "The Wikipedia article [A] has read the most times",
  "What [A]'s search history reveals about them",
  "The most believable excuse [A] could give for being late",
  "What [A]'s theme song would be, and why it's embarrassing",
  "The business [A] would definitely start and immediately regret",
  "What [A] would be arrested for in a Hallmark movie",
  "What [A] orders at a restaurant that makes the waiter sigh",
  "The superpower [A] would misuse immediately",
  "What [A]'s diary entry from last Tuesday probably says",
  "The red flag [A] displays that everyone politely ignores",
  "What [A] and [B] would start a podcast about",
  "The cult [A] would accidentally found",
  "What [A] is definitely the villain of, but doesn't know it",
  "The TV show [A]'s life is most like, and which character they are",
  "What [A] would do with a million dollars in 48 hours",
  "The award [A] would win at a work party that nobody wants",
  "What [A] texts back immediately vs leaves on read for three days",
  "The job [A] was born to do that doesn't exist yet",
  "Why [A] and [B] would not survive together in an apocalypse",
  "The thing [A] is weirdly competitive about",
  "The reality show [A] would absolutely win",
  "What [A] would write in their Yelp review of heaven",
  "What [A] brings to every potluck no matter what",
  "The hobby [A] picked up during lockdown that they pretend they still do",
  "What [A]'s pet would say about them in a court of law",
  "What [A] says vs what [A] means",
  "The career [A] would have in a medieval village",
  "What [A] would rename themselves if they could",
  "The most [A]-coded purchase ever made on Amazon",
  "What [A] is doing right now instead of being productive",
  "The thing [A] knows way too much about for no reason",
  "What [A] and [B]'s buddy cop movie would be called",
  "The most likely reason [A] has been blocked by someone",
  "The talent show act [A] has been quietly rehearsing",
  "What [A]'s autobiography would be titled",
  "The era of history [A] would thrive in",
  "What [A] definitely Googled after leaving this room",
  "The most suspicious item on [A]'s grocery list",
  "What [A]'s sleep paralysis demon looks like",
  "The most passive-aggressive gift [A] has ever given",
  "What [A] would do if they were invisible for a day",
  "The reason [A] and [B] would get kicked off a game show",
  "The world record [A] could probably break without trying",
  "What [A] argues about with strangers on the internet",
  "The thing [A] does that they think nobody notices",
  "What [A]'s warning label would say",
  "The fake name [A] gives at Starbucks and why",
  "What [A] is the patron saint of",
  "The documentary Netflix would make about [A]",
  "What [A] would say as their last words, and why it'd be embarrassing",
  "The secret talent [A] definitely has but refuses to admit",
];

export function buildPersonalizedPool(players, totalPromptsNeeded) {
  const names = players.map(p => p.name);
  const shuffledTemplates = [...PERSONAL_PROMPT_TEMPLATES].sort(() => Math.random() - 0.5);
  const result = [];

  let templateIdx = 0;
  let playerQueue = [];

  const nextPlayer = (exclude) => {
    if (!playerQueue.length) playerQueue = [...names].sort(() => Math.random() - 0.5);
    if (exclude && playerQueue[0] === exclude && playerQueue.length > 1) {
      playerQueue.push(playerQueue.shift());
    }
    return playerQueue.shift();
  };

  while (result.length < totalPromptsNeeded) {
    if (templateIdx >= shuffledTemplates.length) {
      shuffledTemplates.sort(() => Math.random() - 0.5);
      templateIdx = 0;
    }
    const template = shuffledTemplates[templateIdx++];
    const a = nextPlayer(null);
    const b = nextPlayer(a);
    result.push(template.replace(/\[A\]/g, a).replace(/\[B\]/g, b));
  }

  return result;
}

export function interleavePersonal(regularPool, personalPool, promptsPerRound, numPlayers) {
  const personalPerRound = Math.min(promptsPerRound, numPlayers);
  const regularPerRound = promptsPerRound - personalPerRound;

  const shuffledRegular = [...regularPool].sort(() => Math.random() - 0.5);
  const combined = [];
  let regIdx = 0;
  let perIdx = 0;

  const rounds = Math.ceil(shuffledRegular.length / Math.max(1, regularPerRound));
  for (let r = 0; r < rounds && perIdx < personalPool.length; r++) {
    for (let i = 0; i < personalPerRound && perIdx < personalPool.length; i++) {
      combined.push(personalPool[perIdx++]);
    }
    for (let i = 0; i < regularPerRound && regIdx < shuffledRegular.length; i++) {
      combined.push(shuffledRegular[regIdx++]);
    }
  }
  while (regIdx < shuffledRegular.length) combined.push(shuffledRegular[regIdx++]);
  return combined;
}
